proxmox_host      = "https://192.168.0.131:8006/api2/json"
target_node       = "proxmox"
storage           = "samsung-ssd"
full_clone        = true
template_name     = "ubuntu-web-server-base"
network_bridge    = "vmbr0"
memory            = 2064
name              = "barometro" # This will be a unique sha from the pipeline.
environment       = "dev"